# Generated by Django 5.2.7 on 2025-11-02 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Formato: NNNN/TT/AA', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoPermanente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de 15 dígitos do processo permanente.', max_length=15, unique=True)),
                ('data_encontrado', models.DateTimeField(blank=True, null=True)),
                ('encontrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_encontrados', to=settings.AUTH_USER_MODEL)),
                ('listagem_encontrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listagem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_digitado', models.CharField(max_length=15)),
                ('e_permanente', models.BooleanField(default=False)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('listagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.listagem')),
            ],
            options={
                'unique_together': {('listagem', 'numero_digitado')},
            },
        ),
    ]
