# Generated by Django 5.2.7 on 2026-01-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processopermanente',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto'),
        ),
        migrations.AddField(
            model_name='processopermanente',
            name='caixa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caixa'),
        ),
        migrations.AddField(
            model_name='processopermanente',
            name='classe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='processopermanente',
            name='localizador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localizador'),
        ),
        migrations.AddField(
            model_name='processopermanente',
            name='orgao_atual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão Atual'),
        ),
        migrations.AddField(
            model_name='processopermanente',
            name='situacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='processopermanente',
            name='situacao_detalhe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação Detalhe'),
        ),
    ]
